name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin
      volumes:
        - $GITHUB_WORKSPACE:/volume
      options: --security-opt seccomp=unconfined

    steps:
      - uses: actions/checkout@master
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo tarpaulin -v --out Xml
      - name: Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
